version: '3.1'

services:

  app:
    image: appsosmed:latest
    restart: always
    ports:
      - 8083:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: dbsosmed
      MYSQL_USER: devopscilsy
      MYSQL_PASSWORD: 1234567890

    volumes:
      - db:/var/lib/mysql
      - ./.server:/docker-entrypoint-initdb.d

volumes:
  db: